title: Instamancer
logo: /assets/img/logo.png
description: Scrape Instagram's API with Puppeteer.
show_downloads: false
theme: jekyll-theme-minimal
repository: ScriptSmith/instamancer
google_analytics: UA-79900226-3
